Include confounds in dual regression stage 2

diff --git a/code/dual_regression b/code/dual_regression
--- a/code/dual_regression
+++ b/code/dual_regression
@@ -4,6 +4,8 @@
 #
 #   Stephen Smith, Christian Beckmann, Janine Bijsterbosch, Sam Harrison, FMRIB Image Analysis Group
 #
+#   R21 modification: include run-specific nuisance confounds in stage 2.
+#
 #   Copyright (C) 2011-2019 University of Oxford
 #
 #   Part of FSL - FMRIB's Software Library
@@ -74,12 +76,12 @@ export LC_ALL=C
 Usage() {
     cat <<EOF
 
-dual_regression v0.6
+dual_regression v0.6 (R21 confound modification)
 
 ***NOTE*** ORDER OF COMMAND-LINE ARGUMENTS IS DIFFERENT FROM PREVIOUS VERSION
 
-Usage: dual_regression <group_IC_maps> <des_norm> <design.mat> <design.con> <n_perm> [--thr] <output_directory> <input1> <input2> <input3> .........
-e.g.   dual_regression groupICA.gica/groupmelodic.ica/melodic_IC 1 design.mat design.con 500 grot \`cat groupICA.gica/.filelist\`
+Usage: dual_regression <group_IC_maps> <des_norm> <design.mat> <design.con> <n_perm> [--thr] <output_directory> <input1> <confounds1> <input2> <confounds2> .........
+e.g.   dual_regression groupICA.gica/groupmelodic.ica/melodic_IC 1 design.mat design.con 500 grot input1.nii.gz confounds1.tsv input2.nii.gz confounds2.tsv
 
 <group_IC_maps_4D>            4D image containing spatial IC maps (melodic_IC) from the whole-group ICA analysis
 <des_norm>                    0 or 1 (1 is recommended). Whether to variance-normalise the timecourses used as the stage-2 regressors
@@ -88,7 +90,12 @@ e.g.   dual_regression groupICA.gica/groupmelodic.ica/melodic_IC 1 design.mat de
 <n_perm>                      Number of permutations for randomise; set to 1 for just raw tstat output, set to 0 to not run randomise at all.
 [--thr]                       Perform thresholded dual regression to obtain unbiased timeseries for connectomics analyses (e.g., with FSLnets)
 <output_directory>            This directory will be created to hold all output and logfilesg
-<input1> <input2> ...         List all subjects' preprocessed, standard-space 4D datasets
+<input1> <input2> ...         Subjects' preprocessed, standard-space 4D datasets
+<confounds1> <confounds2> ... Matching numeric confound matrices (one row per volume, no header)
+
+Each input dataset must be followed immediately by its matching confound matrix.
+The confounds are appended to the stage-1 network timecourses for stage 2 only.
+Stage-2 outputs contain only the spatial maps for the original group ICs.
 
 <design.mat> <design.con>     can be replaced with just
 -1                            for group-mean (one-group t-test) modelling.
@@ -104,7 +111,7 @@ zeropad() {
 
 ############################################################################
 
-[ "$6" = "" ] && Usage
+[ "$7" = "" ] && Usage
 
 ORIG_COMMAND=$*
 
@@ -136,8 +143,17 @@ fi
 OUTPUT=`${FSLDIR}/bin/remove_ext $1` ; shift
 
 while [ _$1 != _ ] ; do
+  if [ _$2 = _ ] ; then
+    echo "ERROR: each input dataset must be followed by a confound matrix" >&2
+    Usage
+  fi
+  if [ ! -f "$2" ] ; then
+    echo "ERROR: confound matrix not found: $2" >&2
+    exit 1
+  fi
   INPUTS="$INPUTS `${FSLDIR}/bin/remove_ext $1`"
-  shift
+  CONFOUNDS="$CONFOUNDS $2"
+  shift 2
 done
 
 ############################################################################
@@ -172,10 +188,20 @@ ID_drB=`$FSLDIR/bin/fsl_sub -j $ID_drA -T 5 -N mask_generation2 -l $LOGDIR ${LOG
 
 echo "doing the dual regressions"
 j=0
+set -- $CONFOUNDS
 for i in $INPUTS ; do
   s=subject`zeropad $j 5`
+  c=$1
+  shift
   echo "$FSLDIR/bin/fsl_glm -i $i -d $ICA_MAPS -o $OUTPUT/dr_stage1_${s}.txt --demean -m $OUTPUT/mask ; \
-        $FSLDIR/bin/fsl_glm -i $i -d $OUTPUT/dr_stage1_${s}.txt -o $OUTPUT/dr_stage2_$s --out_z=$OUTPUT/dr_stage2_${s}_Z --demean -m $OUTPUT/mask $DES_NORM ; \
+        npts=\`$FSLDIR/bin/fslnvols $i\` ; \
+        nconf=\`awk 'END { print NR }' $c\` ; \
+        if [ \$npts -ne \$nconf ]; then echo "ERROR: $c has \$nconf rows but $i has \$npts volumes" >&2; exit 1; fi ; \
+        paste $OUTPUT/dr_stage1_${s}.txt $c > $OUTPUT/dr_stage2_${s}_design.txt ; \
+        $FSLDIR/bin/fsl_glm -i $i -d $OUTPUT/dr_stage2_${s}_design.txt -o $OUTPUT/dr_stage2_${s}_all --out_z=$OUTPUT/dr_stage2_${s}_all_Z --demean -m $OUTPUT/mask $DES_NORM ; \
+        $FSLDIR/bin/fslroi $OUTPUT/dr_stage2_${s}_all $OUTPUT/dr_stage2_$s 0 $N_ICs ; \
+        $FSLDIR/bin/fslroi $OUTPUT/dr_stage2_${s}_all_Z $OUTPUT/dr_stage2_${s}_Z 0 $N_ICs ; \
+        $FSLDIR/bin/imrm $OUTPUT/dr_stage2_${s}_all $OUTPUT/dr_stage2_${s}_all_Z ; \
         $FSLDIR/bin/fslsplit $OUTPUT/dr_stage2_$s $OUTPUT/dr_stage2_${s}_ic" >> ${LOGDIR}/drC
   j=`echo "$j 1 + p" | dc`
 done
